name: Bundle Lua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.x

      - name: Install luabundler
        run: npm install -g luabundler

      - name: Make merge.sh executable
        run: chmod +x ./merge.sh

      - name: Bundle
        run: ./merge.sh

      - uses: actions/upload-artifact@v4.6.2
        with:
          path: build/projaimbot.lua
          name: projaimbot.zip
